services:
    netgen_layouts.ezplatform.admin.controller.base:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Controller\Admin\Controller
        abstract: true
        calls:
            - [setContainer, ["@service_container"]]
            - [checkPermissions]

    netgen_layouts.ezplatform.admin.controller.location_layouts:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Controller\Admin\LocationLayouts
        public: true
        parent: netgen_layouts.ezplatform.admin.controller.base
        arguments:
            - "@ezpublish.api.service.content"
            - "@netgen_layouts.layout.resolver"
            - "@netgen_layouts.ezplatform.admin.related_layouts_loader"

    netgen_layouts.ezplatform.admin.controller.layout_wizard:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Controller\Admin\LayoutWizard
        public: true
        parent: netgen_layouts.ezplatform.admin.controller.base
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@netgen_layouts.layout.registry.layout_type"

    netgen_layouts.ezplatform.admin.controller.layout_wizard_callback:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Controller\Admin\LayoutWizardCallback
        public: true
        parent: netgen_layouts.ezplatform.admin.controller.base
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@netgen_layouts.api.service.layout_resolver"

    netgen_layouts.ezplatform.event_listener.admin.main_menu_builder:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\EventListener\Admin\MainMenuBuilderListener
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.ezplatform.event_listener.admin.set_page_layout:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\EventListener\Admin\SetPageLayoutListener
        arguments:
            - "@request_stack"
            - "%ezpublish.siteaccess.groups_by_siteaccess%"
            - "%netgen_layouts.ezplatform.admin.pagelayout%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.ezplatform.event_listener.admin.cache_enabled:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\EventListener\Admin\CacheEnabledListener
        arguments:
            - "@netgen_layouts.http_cache.client"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.ezplatform.event_listener.admin.is_enterprise_version:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\EventListener\Admin\IsEnterpriseVersionListener
        arguments:
            - "%kernel.bundles%"
        tags:
            - { name: kernel.event_subscriber }

    netgen_layouts.ezplatform.admin.related_layouts_loader:
        class: Netgen\Layouts\Ez\AdminUI\RelatedLayoutsLoader
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@database_connection"

    netgen_layouts.ezplatform.admin.tab.location_view.layouts:
        class: Netgen\Layouts\Ez\AdminUI\Tab\LocationView\LayoutsTab
        arguments:
            - "@twig"
            - "@translator"
            - "@event_dispatcher"
            - "@eZ\\Publish\\API\\Repository\\PermissionResolver"
            - "@security.authorization_checker"
            - "@router"
        tags:
            - { name: ezplatform.tab, group: location-view }

    netgen_layouts.ezplatform.admin.component.stylesheets:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         arguments:
             - "@twig"
             - "@@ezdesign/nglayouts/stylesheets.html.twig"
         tags:
             - { name: ezplatform.admin_ui.component, group: stylesheet-head }

    netgen_layouts.ezplatform.admin.component.javascripts:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         arguments:
             - "@twig"
             - "@@ezdesign/nglayouts/javascripts.html.twig"
         tags:
             - { name: ezplatform.admin_ui.component, group: script-body }
