services:
    netgen_layouts.ezplatform.form.content_type:
        class: Netgen\Layouts\Ez\Form\ContentTypeType
        arguments:
            - "@ezpublish.api.service.content_type"
        tags:
            - { name: form.type }

    netgen_layouts.ezplatform.form.section:
        class: Netgen\Layouts\Ez\Form\SectionType
        arguments:
            - "@ezpublish.api.service.section"
        tags:
            - { name: form.type }

    netgen_layouts.ezplatform.form.object_state:
        class: Netgen\Layouts\Ez\Form\ObjectStateType
        arguments:
            - "@ezpublish.api.service.object_state"
        tags:
            - { name: form.type }

    netgen_layouts.ezplatform.form.admin.layout_wizard:
        class: Netgen\Bundle\LayoutsEzPlatformBundle\Form\Admin\Type\LayoutWizardType
        arguments:
            - "@netgen_layouts.api.service.layout"
            - "@netgen_layouts.layout.registry.layout_type"
            - "%netgen_admin_ui.layouts.is_enterprise%"
        tags:
            - { name: form.type }
